### ISSUE TITLE
使用 yaml 来管理插件

### ISSUE THREAD

**Issue by weirongxu** [vim-china/reading-vimrc#1]
https://github.com/weirongxu/dotvim/blob/984a90298664e902eeb44eedc8081ac001002738/vimrc.rc.vim

来开个头  
之前从`neobundle`迁移到`dein.vim`挺费劲的，途中就折腾了这个方案。  
代码有点多，不吝赐教

**Comment by chemzqm** [comment]
个人还是喜欢原始的一行一个插件方式，那样更容易使用二分法找出 bug 插件。

**Comment by chemzqm** [comment]
我也尝试用过 dein.vim, 然而发现这货的缓存常常导致我修改插件后无法生效，另一点就是不支持自动 rebase， 我没办法修改插件同时保持更新。

**Comment by wsdjeg** [comment]
可以的，你加入插件是使用unmerged 特性

**Comment by weirongxu** [comment]
dein.vim 不能自动 lock 插件的版本，经常会出现一些插件bug

之前也为了找出一些插件的bug，把**通配符**的include取消了   https://github.com/weirongxu/dotvim/blob/984a90298664e902eeb44eedc8081ac001002738/plugins/index.rc.yml

**Comment by wsdjeg** [comment]
我打算写一点关于 dein 这个插件管理器的教程，其实在我看来这个插件管理器已经在 neobundle 基础上完善太多了，该有的功能几乎都有，我暂时找不到什么可以挑剔的地方。

**Comment by weirongxu** [comment]
虽然是用 yaml 来管理插件，但是底层还是 dein.vim 的

**Comment by wsdjeg** [comment]
我开了一个 PR，打算以这个title为主题，讨论下你这个仓库呀，如果有什么说的不对的可以指出呀
