### ISSUE TITLE
Vim配置

### ISSUE THREAD

**Issue by neur1n** [vim-china/reading-vimrc#11]
https://github.com/Neur1n/dotfiles/tree/43b094dae7db5c1ddc035d3d9700075e08c27386/vim

主要是在Windows 10下用GVim，之前主要是写Python，不过也没有什么专用插件。

- 主要就是自动补全和linting
- statusline是参考lightline写的，tabline似乎有点复杂就没写
- 参考airline的插件把warning和error从`loclist()`里提取出来显示
- 写了几个运行/编译代码的函数，似乎能用`make`代替，但是懒得移植了

**Comment by wsdjeg** [comment]
基本上没发现什么问题，只有一个 map Q，这个建议用  noremap

**Comment by wsdjeg** [comment]
基本上没发现什么问题，只有一个 map Q，这个建议用  noremap

**Comment by neur1n** [comment]
哇，我忘了这个issue，谢谢阅读。在tg群里也学习了不少。

**Comment by wsdjeg** [comment]
是的，tg群目前还比较活跃

________________________________
wsdjeg@outlook.com

发件人： J<mailto:notifications@github.com>
发送时间： 2018-12-22 20:23
收件人： vim-china/reading-vimrc<mailto:reading-vimrc@noreply.github.com>
抄送： Wang Shidong<mailto:wsdjeg@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [vim-china/reading-vimrc] Vim配置 (#11)

哇，我忘了这个issue，谢谢阅读。在tg群里也学习了不少。
