### ISSUE TITLE
Vim配置

### ISSUE THREAD

**Issue by glepnir** [vim-china/reading-vimrc#15]
[commit7b2c422](https://github.com/taigacute/ThinkVim/commit/7b2c422d37dc3054710556a6933704b41cf33f38)
欢迎指正

**Comment by wsdjeg** [comment]
不好意思，看到的太晚了，我说怎么 bio 这么熟悉呢。看到你分享在 v2 的帖子，颜色主题非常不错。

**Comment by glepnir** [comment]
@wsdjeg  主题也是fork改的 不是我自己写的。我是站在巨人的肩膀上。和你的项目是没法比的。我这个就是自己的小配置分享一下愿意折腾的人。不愿意折腾的 我的文章都还是推荐你的项目入门
