### ISSUE TITLE
Vimrc 求指导

### ISSUE THREAD

**Issue by Duan-JM** [vim-china/reading-vimrc#16]
[vimrc 链接](https://github.com/VDeamoV/VDeamoV-vimrc/blob/master/vimrc)

我的 vimrc 继承于一些大佬的 vimrc，后期经过自己的修改，更换了一些插件～

目前存在的问题如下：
1. 有时候会有一点小卡。
2. 针对 pytorch 的补全有一些问题。

希望大佬能提供一些建议，以及一些插件的推荐。

**Comment by wsdjeg** [comment]
```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  augroup vimplug
    au!
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  augroup END
endif
```

第一行用 `filereadable()`

同样的 `map` 建议改成 `nnoremap`

autocmd 应该都要放到 augroup 里。

**Comment by Duan-JM** [comment]
@wsdjeg 感谢呀，按照建议修改啦～再次感谢大佬的指点
