### ISSUE TITLE
bramblex's BlxVimrc

### ISSUE THREAD

**Issue by wsdjeg** [vim-china/reading-vimrc#2]
@bramblex
你好，上次v2ex上未完成的，后面会在这个仓库下面完成。

https://github.com/bramblex/BlxVimrc/tree/fb0689fec6c49e7dc53e5f7813cdd6cf574cfbf9

**Comment by bramblex** [comment]
喵喵喵？OwO 什么情况？

**Comment by wsdjeg** [comment]
是这样的，我在做 vim-china 这个社区，目前开了6个仓库分别做不同的事情。这个仓库主要是想阅读一些vimrc，一来是帮review一下，而来是想提炼一些创意的思想。有点像上次在v2ex上的活动，当时你也留下了链接，但是我没来得及看。
