### ISSUE TITLE
logo.png is copy of vim-jp/reading-vimrc

### ISSUE THREAD

**Issue by mattn** [vim-china/reading-vimrc#20]
Hi, all.

I'm grad to see that you are working on vim-china/reading-vimrc as similar to vim-jp/reading-vimrc. :+1:
BTW, logo.png in this repository seems to be copied from vim-jp/reading-vimrc. We vim-jp had to put LICENSE file in vim-jp/reading-vimrc. We did put [CC-BY-4.0 LICENSE file](https://github.com/vim-jp/vim-jp.github.io/commit/6f6ed494ee457d8278d58963f0e6778bf649effd) in our repository in few minutes before as that https://vim-jp.org is under the CC-BY-4.0 LICENSE. We don't mind that someone use this logo.png but I'm thinking we've better to observe the rules. :-)

Please add notice in README.md that you did copy it from vim-jp/reading-vimrc.

Thanks.

**Comment by wsdjeg** [comment]
Ok, I will add the note in readme.

**Comment by wsdjeg** [comment]
closed in https://github.com/vim-china/reading-vimrc/commit/7d9675ea172e123f795a690355be67ecd97b56e6

**Comment by mattn** [comment]
Thank you.
