### ISSUE TITLE
使用 Vundle 来管理插件

### ISSUE THREAD

**Issue by floatval** [vim-china/reading-vimrc#4]
https://github.com/floatval/backup-vimrc/blob/5ccefa09c228569f096eb47c35333a4b200c0a24/vimrc
另外,想请教下,pylint在每次打开python文件时都太慢了,简直是种煎熬,有什么替代品么

**Comment by HankelBao** [comment]
我记得YCM好像本身python就是有lint的为什么还要Plug pylint？
另外我觉得deoplete特别是在安装的友好度上好很多，推荐zchee/deoplete-jedi

**Comment by floatval** [comment]
@HankelBao 谢谢,当时是为了学习pep8的风格,后来觉得亏了...打开速度太慢了
deoplete-jedi听好多人说过了,明天试试.

**Comment by floatval** [comment]
**更新下新的配置,配置文件已进行重构**
https://github.com/floatval/vimrc/tree/2a2c63e0fafb9bdb509e38e73d0ae17a8349ddeb

现在采用异步语法检错，插件是neomake，也可以选择使用ale。这样同时调用两个语法检错插件也不会造成卡顿。
