### ISSUE TITLE
求指导

### ISSUE THREAD

**Issue by 13o4t** [vim-china/reading-vimrc#5]
https://github.com/m75n/dotfiles/blob/5c33438c14a55eb2e6b88124f03df7c8164d4183/.vimrc

东拼西凑来的，很久没动了

**Comment by zhmars** [comment]
Vim 菜鸟，不敢说指导
- 加上适当的条件判断可能会好点，不然这份配置在新机器上启动，第一行就报错了
- 建议插件的配置和 Vim 自身的配置分开写，而不是交叉在一起，方便后期维护
- 可以试试这个工具 [Kuniwak/vint](https://github.com/Kuniwak/vint) ，检查其它不合理的地方

**Comment by floatval** [comment]
关于楼上的提议，具体例子的话可以参照我的。虽然我也是菜鸟。。。https://github.com/floatval/backup-vimrc/blob/5ccefa09c228569f096eb47c35333a4b200c0a24/vimrc
