### ISSUE TITLE
求建议

### ISSUE THREAD

**Issue by gcgc100** [vim-china/reading-vimrc#6]
[.vimrc](https://github.com/gcgc100/mydotfiles/blob/master/.vimrc)
用vundle管理的插件。
python-mode插件不能正常工作，暂时禁掉了，有大神能看出原因吗，求建议。
另外插件里有不少依赖的软件，在新电脑上配置时还是很麻烦，有什么好方法可以全部自动化吗？我现在用的shell脚本，但效果不理想。

**Comment by izhengfan** [comment]
请确认一下是不是 Python 版本的问题。

python-mode 可以指定使用的 Python 版本：

```vim
let g:pymode_python = 'python3'
" or
" let g:pymode_python = 'python'
```

不知道你用的是什么系统和发行版，我猜是 Linux 好了，比如 Ubuntu，Vim 用的是 apt install 安装的 Vim。Ubuntu 下 Vim 的 package 版本有好多，以  16.04 为例，有 `vim-gtk` `vim-gnome` `vim-gtk-py2`  `vim-gnome-py2` 等，有的使用 Python 3 （前两者），有的默认使用 Python 2 （后两者）。请确保它们和 `g:pymode_python` 的设置对应上。

Ubuntu 下切换默认的 vim 版本，可以执行：

```bash
sudo update-alternatives --config vim
```

**Comment by wsdjeg** [comment]
@gcgc100 如果是提问的话，像这类问题，你应该提供如下命令输出结果， 注意用 markdown 格式 `` ``` `` 和 `` ``` `` 包裹：

1. `vim --version`
2. `python --version`
3. `python3/python2 --version`

**Comment by izhengfan** [comment]
@wsdjeg 是不是把提问的规范加到 README 里？

**Comment by wsdjeg** [comment]
暂时不用，因为这个仓库主要还是用户丢vimrc链接，然后讨论，具体格式没什么限制，但是可以增加一篇提问的方式，这点对于社区的每一个仓库都有用。

**Comment by gcgc100** [comment]
@wsdjeg ,好的。pymode的问题我重新测试了一下，已经没有了，猜想应该是和以前用的supertab插件冲突了导致自动补全不能正常工作。
